[package]
authors = ["Alexandra Frydl <me@alexfrydl.com>"]
description = "A core utility library for Rust applications."
edition = "2018"
name = "af-core"
license = "MPL-2.0"
repository = "https://gitlab.com/alexfrydl/lib-rs"
version = "0.1.0"

[package.metadata.docs.rs]
all-features = true

[features]
fs-watch = ["notify"]

[dependencies]
af-macros = { version = "0.1", path = "../af-macros" }
arrayvec = "0.5"
async-channel = "1"
base64 = "0.13"
blocking = "1"
chrono = "0.4"
chrono-tz = "0.5"
derive_more = "0.99"
event-listener = "2"
futures-lite = "1"
glob = "0.3"
itertools = "0.10"
log = "0.4"
num-traits = "0.2"
once_cell = { version = "1", features = ["parking_lot"] }
parking_lot = "0.11"
parse_duration = "2"
rand = "0.8"
rand_xoshiro = "0.6"
serde = "1"
uuid = { version = "0.8", features = ["serde"] }

# fs-watch deps.

notify = { version = "4", optional = true }
